package com.api.payglobal.entity.enums;

public enum TipoSolicitud {
    COMPRA_LICENCIA,
    SOLICITUD_RETIRO_WALLET_DIVIDENDOS,
    SOLICITUD_RETIRO_WALLET_COMISIONES,
    TRANFERENCIA_USUARIO,
    PAGO_DELEGADO,
}
